### ISSUE TITLE
Provider as a class instead of a struct

### ISSUE THREAD

**Issue by Prince2k3** [qutheory/vapor-tls#5]
I have a use case where I want to subclass the TLS provider and use it to jump start another Provider that uses TLS. I can't do that as the Provider is defined as a struct instead of a class. 

I recommend having it as a class instead of a struct in order to allow for use case that allows for subclassing.

**Comment by tanner0101** [comment]
This shouldn't be hard to do. I will incorporate in the next update to Vapor TLS (or feel free to submit a PR)

**Comment by Prince2k3** [comment]
@tannernelson I do have a code updates but I do not have access to this repo to create a PR
